### ISSUE TITLE
Don't display movie poster on Question Screen

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/ionic-app#100]
### Description

Currently small versions of the movie posters are shown on the Question screen. This makes it too easy to guess the correct answer.

### Tasks

- [x] remove small poster images
- [x] refine styles, such that the page does not look too empty

### Context 
#33

**Comment by rschlaefli** [comment]
Doing it, as I needed to refactor the MovieCard a bit for bonus q :)
