### ISSUE TITLE
Failure screen not displaying the correct reason on bonus question failure

### ISSUE THREAD

**Issue by rschlaefli** [kwizapp/ionic-app#103]
### Expected Behaviour
The failure screen shows the correct reason when a bonus question is answered incorrectly.

### Actual Behaviour
The bonus question shows the reason based on the normal question failure, e.g., that "The Shining" is incorrect and it should be "The Shining".

### Steps to Reproduce the Issue
- Answer a bonus question incorrectly

**Comment by nikzaugg** [comment]
@rschlaefli 
Is this fixed?
