### ISSUE TITLE
Double-execution of Points Animations

### ISSUE THREAD

**Issue by rschlaefli** [kwizapp/ionic-app#104]
### Description

The animations related to points sometimes execute twice (another time when the screen is left using "Gamble" for example). I am not sure whether the points are also added twice, or if it is only the animation, but I had the feeling that points calculations were off sometimes as well.

**Comment by nikzaugg** [comment]
The Animation is just triggered again, it's not doing the same thing twice.

The "issue" is that before we go from the Success Screen to the Bonus Question Screen the current gained points are added to the global store, and as the animation always "springs" to the value it is triggered (as now the points are added suddenly). This only happens for a brief moment.

I think that for now we should leave it as it is. We can look at it again if we have time later.
