### ISSUE TITLE
Inconsistencies 

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/ionic-app#149]
### Expected Behaviour
Should have the same styles as if started locally with `npm run dev`

### Actual Behaviour
**Emoji very small**

![image](https://user-images.githubusercontent.com/22471485/81551783-b92d3280-9382-11ea-8cee-4cc949269c35.png)

**Hearts are very tiny...**

![image](https://user-images.githubusercontent.com/22471485/81551849-cf3af300-9382-11ea-8b84-f407ded146af.png)

### Steps to Reproduce the Issue
- start application with `_run.sh`
- guess wrong
- guess correctly

**Comment by nikzaugg** [comment]
it seems that `text-10xl` by tailwind does not properly work?

**Comment by alexscheitlin** [comment]
> it seems that `text-10xl` by tailwind does not properly work?

Yes, this class is not available in the production build (only in the development build).

I've tried to comment the following line in the `postcss.config.js` but this did not change the behaviour:

`...(process.env.NODE_ENV === 'production' ? [purgecss] : []),`

Disabling the `purge` option directly in the `tailwind.config.js` did not help neither. Also whitelisting the classes did not help. See here for the doc : https://tailwindcss.com/docs/controlling-file-size/

**Comment by alexscheitlin** [comment]
Even changing the `xl` font size (default: `1.25rem`) to something else will not have an effect in the production build.

```
    fontSize: {
      ...,
      xl: '7.25rem',
      ...
    },
```

**Comment by alexscheitlin** [comment]
When running `npm run build:style` the css is compiled as expected.

**Comment by alexscheitlin** [comment]
When running `npm run build` the tailwind classes are included in the `main.*.chunk.css` as expected.

**Comment by alexscheitlin** [comment]
When running `docker exec -ti ea036a379167 /bin/sh` and inspecting the css file in the running container, there are no custom tailwind css-styles such as the changed font size for `xl` from above (or the already specified `10xl`).
