### ISSUE TITLE
Game Over Screen 2.0

### ISSUE THREAD

**Issue by alexscheitlin** [kwizapp/ionic-app#90]
### Description

Continuation of the MVP's game over screen from  #39.

### Tasks

- [x] The total number of scores are animated as a counter (e.g., count from 0 to the achieved number of points using [react-countup](https://www.npmjs.com/package/react-countup)).

### Context 

[Story: Game Over Screen](https://github.com/kwizapp/kwiz/issues/17)

**Comment by nikzaugg** [comment]
You can also use `react-spring` for the animation, here is a simple example how to counting can be done:

```js
const Example = () => {
  const [clicked, setClicked] = useState(false);
  const props = useSpring({ countGoal: clicked ? 100 : 0 });

  return (
    <animated.div onClick={(): void => setClicked(!clicked)}>
      {props.countGoal.interpolate((x: number) => x.toFixed(0))}
    </animated.div>
  );
};
```
![counting_animation](https://user-images.githubusercontent.com/22471485/79535129-d3723a00-807c-11ea-9d07-a1dbdac90c18.gif)
